<!-- Hlavní obsah -->
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center">Adresář kontaktů</h1>
            <p class="text-center text-muted">Snadný přístup ke všem vašim kontaktům online.</p>
        </div>
    </div>

    <!-- Vyhledávací pole -->
    <div class="row mt-4">
        <div style="display: flex; flex-direction: column; gap: 1rem; align-items: center;">
            <a href="<?= $this->linkGenerator->generateLink('contact/createForm') ?>" class="btn btn-primary btn-sm">Create new</a>
            <a href="<?= $this->linkGenerator->generateLink('contact/list') ?>" class="btn btn-primary btn-sm">List contacts</a>
        </div>
    </div>
</div>