<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2 style="text-align: center; margin-bottom: 1em">Login</h2>
        <form method="post" action="<?= $this->linkGenerator->generateLink('auth/form', $keepOrigins) ?>">
            <div class="mb-3">
                <label for="login" class="form-label" style="display: none">Login or email:</label>
                <input name="login" id="login" type="text" placeholder="Login or email" required class="form-control"/>
            </div>

            <div class="mb-3">
                <label for="password" class="form-label" style="display: none">Password:</label>
                <input name="password" id="password" type="password" placeholder="Password" required class="form-control"/>
            </div>

            <div style="display: flex; justify-content: center">
                <input type="submit" value="Sign in" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>