<h2 style="text-align: center; margin-bottom: 1em">Login</h2>
<form method="post" action="/root/auth/form" style="padding: 0 2em; display: grid; grid-template-columns: 1fr 1fr; row-gap: 0.5em">
    <label for="login" style="grid-column: 1">Login:</label>
    <input name="login" id="login" type="text" required style="grid-column: 2"/>

    <label for="password" style="grid-column: 1">Password:</label>
    <input name="password" id="password" type="password" required style="grid-column: 2"/>

    <input type="submit" value="sign in" style="grid-column: 1 / span 2"/>
</form>