<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adresář kontaktů</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="?route=home">Adresář kontaktů</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="?route=home">Domů</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="?route=home/authreq">TEST_AUTENTIKACE</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->linkGenerator->generateLink('sign/in', $createOrigins) ?>">Přihlásit se</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $this->linkGenerator->generateLink('sign/out', $createOrigins) ?>">Odhlásit se</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container md-4">